ExemploCanvas:

<ExemploCanvas>:
    # Para criar uma cruz precisamos de 2 objetos Line
    canvas:
        # Um objeto Line deverá ir do meio da base até o meio do topo
        Line:
            points: (self.width/2, 0, self.width/2, self.height)
            width: 2

        # O outro objeto Line deverá ir do meio da direita até o meio da esquerda
        Line:
            points: (0, self.height/2, self.width, self.height/2)
            width: 2