ExemploImagens:

<ExemploImagens@GridLayout>:
    cols: 3
    Image:
        # Pesquisar a imagem
        source: 'images/lab_logo.png'
    Image:
        source: 'images/cake.jpg'

        # Permite redimenzionar a imagem conforme
        # o tamanho da tela
        allow_stretch: True

    Image:
        source: 'images/cake.jpg'

        # Permite não manter as dimesões corretas
        # da imagem
        allow_stretch: True
        keep_ratio: False