ExemploCanvas:

<ExemploCanvas>:
    canvas:
        # Desenhar uma linha
        Line:
            # Uma linha é a ligação entre 2 pontos ou mais
            # Sempre o primeiro sendo o eixo X e o segundo o eixo Y
            points: (0, 0, self.width/4, 100, self.width/2, 0, self.width*3/4, 100, self.width, 0)

            # Podemos aumentar a expressura da linha
            width: 2
