ExemploStackLayout:

<ExemploStackLayout>:
    # A orientação não é "vertical" ou "horizontal"
    # Aqui é por direção (right, left, top, bottom)
    # r: right
    # l: left
    # t: top
    # b: bottom
    orientation: 'lr-bt'
               #l      #t      #r      #b
    padding: ('20dp', '20dp', '20dp', '20dp')  # espaço entre as margens
              #h      #v
    spacing: '20dp', '20dp'  # Espaço entre os widgets
