<MenuWidget>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.8

        Rectangle:
            size: self.size
            
    Label:
        text: 'TÍTULO'
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}

    Button:
        text: 'OK'
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        size_hint: 0.2, 0.1
        # root.parent pois criaremos a função no "main.py"
        # não no "menu.py"
        on_press: root.parent.botao_menu()